// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksSearch.Models;

namespace ParksSearch.Migrations
{
    [DbContext(typeof(ParksSearchContext))]
    [Migration("20210403235732_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksSearch.Models.NationalPark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool?>("WheelchairAccess")
                        .IsRequired()
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "3002 Mt Angeles Rd, Port Angeles, WA",
                            Name = "Olympic Park",
                            WheelchairAccess = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "55210 238th Avenue East, Ashford, WA",
                            Name = "Mountain Rainier Park",
                            WheelchairAccess = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "3256 Road, Paradise, WA",
                            Name = "Paradise",
                            WheelchairAccess = true
                        });
                });

            modelBuilder.Entity("ParksSearch.Models.StatePark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool?>("WheelchairAccess")
                        .IsRequired()
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("StateParks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "5300 116th Ave NE, Kirkland, WA",
                            Name = "Bridle Trails",
                            WheelchairAccess = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "555 NE, Kenmore, WA",
                            Name = "Saint Edward",
                            WheelchairAccess = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "1111 NE 136 St, Poulsbo, WA",
                            Name = "Kitsap Memorial",
                            WheelchairAccess = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
